[package]
name = "evo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.7.1"
libc = "0.2"
goblin = "0.2.0"
# memmap2 = "0.9.4"