#ifndef TFLITE_READER_H
#define TFLITE_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "M001"
#undef flatbuffers_extension
#define flatbuffers_extension "tflitemeta"


typedef const struct tflite_AssociatedFile_table *tflite_AssociatedFile_table_t;
typedef struct tflite_AssociatedFile_table *tflite_AssociatedFile_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_AssociatedFile_vec_t;
typedef flatbuffers_uoffset_t *tflite_AssociatedFile_mutable_vec_t;
typedef const struct tflite_FeatureProperties_table *tflite_FeatureProperties_table_t;
typedef struct tflite_FeatureProperties_table *tflite_FeatureProperties_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_FeatureProperties_vec_t;
typedef flatbuffers_uoffset_t *tflite_FeatureProperties_mutable_vec_t;
typedef const struct tflite_ImageSize_table *tflite_ImageSize_table_t;
typedef struct tflite_ImageSize_table *tflite_ImageSize_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_ImageSize_vec_t;
typedef flatbuffers_uoffset_t *tflite_ImageSize_mutable_vec_t;
typedef const struct tflite_ImageProperties_table *tflite_ImageProperties_table_t;
typedef struct tflite_ImageProperties_table *tflite_ImageProperties_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_ImageProperties_vec_t;
typedef flatbuffers_uoffset_t *tflite_ImageProperties_mutable_vec_t;
typedef const struct tflite_AudioProperties_table *tflite_AudioProperties_table_t;
typedef struct tflite_AudioProperties_table *tflite_AudioProperties_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_AudioProperties_vec_t;
typedef flatbuffers_uoffset_t *tflite_AudioProperties_mutable_vec_t;
typedef const struct tflite_BoundingBoxProperties_table *tflite_BoundingBoxProperties_table_t;
typedef struct tflite_BoundingBoxProperties_table *tflite_BoundingBoxProperties_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_BoundingBoxProperties_vec_t;
typedef flatbuffers_uoffset_t *tflite_BoundingBoxProperties_mutable_vec_t;
typedef const struct tflite_ValueRange_table *tflite_ValueRange_table_t;
typedef struct tflite_ValueRange_table *tflite_ValueRange_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_ValueRange_vec_t;
typedef flatbuffers_uoffset_t *tflite_ValueRange_mutable_vec_t;
typedef const struct tflite_Content_table *tflite_Content_table_t;
typedef struct tflite_Content_table *tflite_Content_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_Content_vec_t;
typedef flatbuffers_uoffset_t *tflite_Content_mutable_vec_t;
typedef const struct tflite_NormalizationOptions_table *tflite_NormalizationOptions_table_t;
typedef struct tflite_NormalizationOptions_table *tflite_NormalizationOptions_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_NormalizationOptions_vec_t;
typedef flatbuffers_uoffset_t *tflite_NormalizationOptions_mutable_vec_t;
typedef const struct tflite_ScoreCalibrationOptions_table *tflite_ScoreCalibrationOptions_table_t;
typedef struct tflite_ScoreCalibrationOptions_table *tflite_ScoreCalibrationOptions_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_ScoreCalibrationOptions_vec_t;
typedef flatbuffers_uoffset_t *tflite_ScoreCalibrationOptions_mutable_vec_t;
typedef const struct tflite_ScoreThresholdingOptions_table *tflite_ScoreThresholdingOptions_table_t;
typedef struct tflite_ScoreThresholdingOptions_table *tflite_ScoreThresholdingOptions_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_ScoreThresholdingOptions_vec_t;
typedef flatbuffers_uoffset_t *tflite_ScoreThresholdingOptions_mutable_vec_t;
typedef const struct tflite_BertTokenizerOptions_table *tflite_BertTokenizerOptions_table_t;
typedef struct tflite_BertTokenizerOptions_table *tflite_BertTokenizerOptions_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_BertTokenizerOptions_vec_t;
typedef flatbuffers_uoffset_t *tflite_BertTokenizerOptions_mutable_vec_t;
typedef const struct tflite_SentencePieceTokenizerOptions_table *tflite_SentencePieceTokenizerOptions_table_t;
typedef struct tflite_SentencePieceTokenizerOptions_table *tflite_SentencePieceTokenizerOptions_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_SentencePieceTokenizerOptions_vec_t;
typedef flatbuffers_uoffset_t *tflite_SentencePieceTokenizerOptions_mutable_vec_t;
typedef const struct tflite_RegexTokenizerOptions_table *tflite_RegexTokenizerOptions_table_t;
typedef struct tflite_RegexTokenizerOptions_table *tflite_RegexTokenizerOptions_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_RegexTokenizerOptions_vec_t;
typedef flatbuffers_uoffset_t *tflite_RegexTokenizerOptions_mutable_vec_t;
typedef const struct tflite_ProcessUnit_table *tflite_ProcessUnit_table_t;
typedef struct tflite_ProcessUnit_table *tflite_ProcessUnit_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_ProcessUnit_vec_t;
typedef flatbuffers_uoffset_t *tflite_ProcessUnit_mutable_vec_t;
typedef const struct tflite_Stats_table *tflite_Stats_table_t;
typedef struct tflite_Stats_table *tflite_Stats_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_Stats_vec_t;
typedef flatbuffers_uoffset_t *tflite_Stats_mutable_vec_t;
typedef const struct tflite_TensorGroup_table *tflite_TensorGroup_table_t;
typedef struct tflite_TensorGroup_table *tflite_TensorGroup_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_TensorGroup_vec_t;
typedef flatbuffers_uoffset_t *tflite_TensorGroup_mutable_vec_t;
typedef const struct tflite_TensorMetadata_table *tflite_TensorMetadata_table_t;
typedef struct tflite_TensorMetadata_table *tflite_TensorMetadata_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_TensorMetadata_vec_t;
typedef flatbuffers_uoffset_t *tflite_TensorMetadata_mutable_vec_t;
typedef const struct tflite_CustomMetadata_table *tflite_CustomMetadata_table_t;
typedef struct tflite_CustomMetadata_table *tflite_CustomMetadata_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_CustomMetadata_vec_t;
typedef flatbuffers_uoffset_t *tflite_CustomMetadata_mutable_vec_t;
typedef const struct tflite_SubGraphMetadata_table *tflite_SubGraphMetadata_table_t;
typedef struct tflite_SubGraphMetadata_table *tflite_SubGraphMetadata_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_SubGraphMetadata_vec_t;
typedef flatbuffers_uoffset_t *tflite_SubGraphMetadata_mutable_vec_t;
typedef const struct tflite_ModelMetadata_table *tflite_ModelMetadata_table_t;
typedef struct tflite_ModelMetadata_table *tflite_ModelMetadata_mutable_table_t;
typedef const flatbuffers_uoffset_t *tflite_ModelMetadata_vec_t;
typedef flatbuffers_uoffset_t *tflite_ModelMetadata_mutable_vec_t;
#ifndef tflite_AssociatedFile_file_identifier
#define tflite_AssociatedFile_file_identifier "M001"
#endif
/* deprecated, use tflite_AssociatedFile_file_identifier */
#ifndef tflite_AssociatedFile_identifier
#define tflite_AssociatedFile_identifier "M001"
#endif
#define tflite_AssociatedFile_type_hash ((flatbuffers_thash_t)0x144a991b)
#define tflite_AssociatedFile_type_identifier "\x1b\x99\x4a\x14"
#ifndef tflite_AssociatedFile_file_extension
#define tflite_AssociatedFile_file_extension "tflitemeta"
#endif
#ifndef tflite_FeatureProperties_file_identifier
#define tflite_FeatureProperties_file_identifier "M001"
#endif
/* deprecated, use tflite_FeatureProperties_file_identifier */
#ifndef tflite_FeatureProperties_identifier
#define tflite_FeatureProperties_identifier "M001"
#endif
#define tflite_FeatureProperties_type_hash ((flatbuffers_thash_t)0x915e45ca)
#define tflite_FeatureProperties_type_identifier "\xca\x45\x5e\x91"
#ifndef tflite_FeatureProperties_file_extension
#define tflite_FeatureProperties_file_extension "tflitemeta"
#endif
#ifndef tflite_ImageSize_file_identifier
#define tflite_ImageSize_file_identifier "M001"
#endif
/* deprecated, use tflite_ImageSize_file_identifier */
#ifndef tflite_ImageSize_identifier
#define tflite_ImageSize_identifier "M001"
#endif
#define tflite_ImageSize_type_hash ((flatbuffers_thash_t)0xcc9516ed)
#define tflite_ImageSize_type_identifier "\xed\x16\x95\xcc"
#ifndef tflite_ImageSize_file_extension
#define tflite_ImageSize_file_extension "tflitemeta"
#endif
#ifndef tflite_ImageProperties_file_identifier
#define tflite_ImageProperties_file_identifier "M001"
#endif
/* deprecated, use tflite_ImageProperties_file_identifier */
#ifndef tflite_ImageProperties_identifier
#define tflite_ImageProperties_identifier "M001"
#endif
#define tflite_ImageProperties_type_hash ((flatbuffers_thash_t)0xaccc9fb9)
#define tflite_ImageProperties_type_identifier "\xb9\x9f\xcc\xac"
#ifndef tflite_ImageProperties_file_extension
#define tflite_ImageProperties_file_extension "tflitemeta"
#endif
#ifndef tflite_AudioProperties_file_identifier
#define tflite_AudioProperties_file_identifier "M001"
#endif
/* deprecated, use tflite_AudioProperties_file_identifier */
#ifndef tflite_AudioProperties_identifier
#define tflite_AudioProperties_identifier "M001"
#endif
#define tflite_AudioProperties_type_hash ((flatbuffers_thash_t)0x5a9de422)
#define tflite_AudioProperties_type_identifier "\x22\xe4\x9d\x5a"
#ifndef tflite_AudioProperties_file_extension
#define tflite_AudioProperties_file_extension "tflitemeta"
#endif
#ifndef tflite_BoundingBoxProperties_file_identifier
#define tflite_BoundingBoxProperties_file_identifier "M001"
#endif
/* deprecated, use tflite_BoundingBoxProperties_file_identifier */
#ifndef tflite_BoundingBoxProperties_identifier
#define tflite_BoundingBoxProperties_identifier "M001"
#endif
#define tflite_BoundingBoxProperties_type_hash ((flatbuffers_thash_t)0x2707d89)
#define tflite_BoundingBoxProperties_type_identifier "\x89\x7d\x70\x02"
#ifndef tflite_BoundingBoxProperties_file_extension
#define tflite_BoundingBoxProperties_file_extension "tflitemeta"
#endif
#ifndef tflite_ValueRange_file_identifier
#define tflite_ValueRange_file_identifier "M001"
#endif
/* deprecated, use tflite_ValueRange_file_identifier */
#ifndef tflite_ValueRange_identifier
#define tflite_ValueRange_identifier "M001"
#endif
#define tflite_ValueRange_type_hash ((flatbuffers_thash_t)0xb82d3e69)
#define tflite_ValueRange_type_identifier "\x69\x3e\x2d\xb8"
#ifndef tflite_ValueRange_file_extension
#define tflite_ValueRange_file_extension "tflitemeta"
#endif
#ifndef tflite_Content_file_identifier
#define tflite_Content_file_identifier "M001"
#endif
/* deprecated, use tflite_Content_file_identifier */
#ifndef tflite_Content_identifier
#define tflite_Content_identifier "M001"
#endif
#define tflite_Content_type_hash ((flatbuffers_thash_t)0xe64bbf58)
#define tflite_Content_type_identifier "\x58\xbf\x4b\xe6"
#ifndef tflite_Content_file_extension
#define tflite_Content_file_extension "tflitemeta"
#endif
#ifndef tflite_NormalizationOptions_file_identifier
#define tflite_NormalizationOptions_file_identifier "M001"
#endif
/* deprecated, use tflite_NormalizationOptions_file_identifier */
#ifndef tflite_NormalizationOptions_identifier
#define tflite_NormalizationOptions_identifier "M001"
#endif
#define tflite_NormalizationOptions_type_hash ((flatbuffers_thash_t)0x8b18c42e)
#define tflite_NormalizationOptions_type_identifier "\x2e\xc4\x18\x8b"
#ifndef tflite_NormalizationOptions_file_extension
#define tflite_NormalizationOptions_file_extension "tflitemeta"
#endif
#ifndef tflite_ScoreCalibrationOptions_file_identifier
#define tflite_ScoreCalibrationOptions_file_identifier "M001"
#endif
/* deprecated, use tflite_ScoreCalibrationOptions_file_identifier */
#ifndef tflite_ScoreCalibrationOptions_identifier
#define tflite_ScoreCalibrationOptions_identifier "M001"
#endif
#define tflite_ScoreCalibrationOptions_type_hash ((flatbuffers_thash_t)0xb57f4355)
#define tflite_ScoreCalibrationOptions_type_identifier "\x55\x43\x7f\xb5"
#ifndef tflite_ScoreCalibrationOptions_file_extension
#define tflite_ScoreCalibrationOptions_file_extension "tflitemeta"
#endif
#ifndef tflite_ScoreThresholdingOptions_file_identifier
#define tflite_ScoreThresholdingOptions_file_identifier "M001"
#endif
/* deprecated, use tflite_ScoreThresholdingOptions_file_identifier */
#ifndef tflite_ScoreThresholdingOptions_identifier
#define tflite_ScoreThresholdingOptions_identifier "M001"
#endif
#define tflite_ScoreThresholdingOptions_type_hash ((flatbuffers_thash_t)0xbc42b0ac)
#define tflite_ScoreThresholdingOptions_type_identifier "\xac\xb0\x42\xbc"
#ifndef tflite_ScoreThresholdingOptions_file_extension
#define tflite_ScoreThresholdingOptions_file_extension "tflitemeta"
#endif
#ifndef tflite_BertTokenizerOptions_file_identifier
#define tflite_BertTokenizerOptions_file_identifier "M001"
#endif
/* deprecated, use tflite_BertTokenizerOptions_file_identifier */
#ifndef tflite_BertTokenizerOptions_identifier
#define tflite_BertTokenizerOptions_identifier "M001"
#endif
#define tflite_BertTokenizerOptions_type_hash ((flatbuffers_thash_t)0xccbde4a5)
#define tflite_BertTokenizerOptions_type_identifier "\xa5\xe4\xbd\xcc"
#ifndef tflite_BertTokenizerOptions_file_extension
#define tflite_BertTokenizerOptions_file_extension "tflitemeta"
#endif
#ifndef tflite_SentencePieceTokenizerOptions_file_identifier
#define tflite_SentencePieceTokenizerOptions_file_identifier "M001"
#endif
/* deprecated, use tflite_SentencePieceTokenizerOptions_file_identifier */
#ifndef tflite_SentencePieceTokenizerOptions_identifier
#define tflite_SentencePieceTokenizerOptions_identifier "M001"
#endif
#define tflite_SentencePieceTokenizerOptions_type_hash ((flatbuffers_thash_t)0x444cd5e5)
#define tflite_SentencePieceTokenizerOptions_type_identifier "\xe5\xd5\x4c\x44"
#ifndef tflite_SentencePieceTokenizerOptions_file_extension
#define tflite_SentencePieceTokenizerOptions_file_extension "tflitemeta"
#endif
#ifndef tflite_RegexTokenizerOptions_file_identifier
#define tflite_RegexTokenizerOptions_file_identifier "M001"
#endif
/* deprecated, use tflite_RegexTokenizerOptions_file_identifier */
#ifndef tflite_RegexTokenizerOptions_identifier
#define tflite_RegexTokenizerOptions_identifier "M001"
#endif
#define tflite_RegexTokenizerOptions_type_hash ((flatbuffers_thash_t)0xf5c69a87)
#define tflite_RegexTokenizerOptions_type_identifier "\x87\x9a\xc6\xf5"
#ifndef tflite_RegexTokenizerOptions_file_extension
#define tflite_RegexTokenizerOptions_file_extension "tflitemeta"
#endif
#ifndef tflite_ProcessUnit_file_identifier
#define tflite_ProcessUnit_file_identifier "M001"
#endif
/* deprecated, use tflite_ProcessUnit_file_identifier */
#ifndef tflite_ProcessUnit_identifier
#define tflite_ProcessUnit_identifier "M001"
#endif
#define tflite_ProcessUnit_type_hash ((flatbuffers_thash_t)0xc3551ce2)
#define tflite_ProcessUnit_type_identifier "\xe2\x1c\x55\xc3"
#ifndef tflite_ProcessUnit_file_extension
#define tflite_ProcessUnit_file_extension "tflitemeta"
#endif
#ifndef tflite_Stats_file_identifier
#define tflite_Stats_file_identifier "M001"
#endif
/* deprecated, use tflite_Stats_file_identifier */
#ifndef tflite_Stats_identifier
#define tflite_Stats_identifier "M001"
#endif
#define tflite_Stats_type_hash ((flatbuffers_thash_t)0x38716202)
#define tflite_Stats_type_identifier "\x02\x62\x71\x38"
#ifndef tflite_Stats_file_extension
#define tflite_Stats_file_extension "tflitemeta"
#endif
#ifndef tflite_TensorGroup_file_identifier
#define tflite_TensorGroup_file_identifier "M001"
#endif
/* deprecated, use tflite_TensorGroup_file_identifier */
#ifndef tflite_TensorGroup_identifier
#define tflite_TensorGroup_identifier "M001"
#endif
#define tflite_TensorGroup_type_hash ((flatbuffers_thash_t)0xa8ffba9)
#define tflite_TensorGroup_type_identifier "\xa9\xfb\x8f\x0a"
#ifndef tflite_TensorGroup_file_extension
#define tflite_TensorGroup_file_extension "tflitemeta"
#endif
#ifndef tflite_TensorMetadata_file_identifier
#define tflite_TensorMetadata_file_identifier "M001"
#endif
/* deprecated, use tflite_TensorMetadata_file_identifier */
#ifndef tflite_TensorMetadata_identifier
#define tflite_TensorMetadata_identifier "M001"
#endif
#define tflite_TensorMetadata_type_hash ((flatbuffers_thash_t)0xce32c1b3)
#define tflite_TensorMetadata_type_identifier "\xb3\xc1\x32\xce"
#ifndef tflite_TensorMetadata_file_extension
#define tflite_TensorMetadata_file_extension "tflitemeta"
#endif
#ifndef tflite_CustomMetadata_file_identifier
#define tflite_CustomMetadata_file_identifier "M001"
#endif
/* deprecated, use tflite_CustomMetadata_file_identifier */
#ifndef tflite_CustomMetadata_identifier
#define tflite_CustomMetadata_identifier "M001"
#endif
#define tflite_CustomMetadata_type_hash ((flatbuffers_thash_t)0xb2ea0a59)
#define tflite_CustomMetadata_type_identifier "\x59\x0a\xea\xb2"
#ifndef tflite_CustomMetadata_file_extension
#define tflite_CustomMetadata_file_extension "tflitemeta"
#endif
#ifndef tflite_SubGraphMetadata_file_identifier
#define tflite_SubGraphMetadata_file_identifier "M001"
#endif
/* deprecated, use tflite_SubGraphMetadata_file_identifier */
#ifndef tflite_SubGraphMetadata_identifier
#define tflite_SubGraphMetadata_identifier "M001"
#endif
#define tflite_SubGraphMetadata_type_hash ((flatbuffers_thash_t)0xb90db5a4)
#define tflite_SubGraphMetadata_type_identifier "\xa4\xb5\x0d\xb9"
#ifndef tflite_SubGraphMetadata_file_extension
#define tflite_SubGraphMetadata_file_extension "tflitemeta"
#endif
#ifndef tflite_ModelMetadata_file_identifier
#define tflite_ModelMetadata_file_identifier "M001"
#endif
/* deprecated, use tflite_ModelMetadata_file_identifier */
#ifndef tflite_ModelMetadata_identifier
#define tflite_ModelMetadata_identifier "M001"
#endif
#define tflite_ModelMetadata_type_hash ((flatbuffers_thash_t)0xa82b9b29)
#define tflite_ModelMetadata_type_identifier "\x29\x9b\x2b\xa8"
#ifndef tflite_ModelMetadata_file_extension
#define tflite_ModelMetadata_file_extension "tflitemeta"
#endif

typedef int8_t tflite_AssociatedFileType_enum_t;
__flatbuffers_define_integer_type(tflite_AssociatedFileType, tflite_AssociatedFileType_enum_t, 8)
#define tflite_AssociatedFileType_UNKNOWN ((tflite_AssociatedFileType_enum_t)INT8_C(0))
#define tflite_AssociatedFileType_DESCRIPTIONS ((tflite_AssociatedFileType_enum_t)INT8_C(1))
#define tflite_AssociatedFileType_TENSOR_AXIS_LABELS ((tflite_AssociatedFileType_enum_t)INT8_C(2))
#define tflite_AssociatedFileType_TENSOR_VALUE_LABELS ((tflite_AssociatedFileType_enum_t)INT8_C(3))
#define tflite_AssociatedFileType_TENSOR_AXIS_SCORE_CALIBRATION ((tflite_AssociatedFileType_enum_t)INT8_C(4))
#define tflite_AssociatedFileType_VOCABULARY ((tflite_AssociatedFileType_enum_t)INT8_C(5))
#define tflite_AssociatedFileType_SCANN_INDEX_FILE ((tflite_AssociatedFileType_enum_t)INT8_C(6))

static inline const char *tflite_AssociatedFileType_name(tflite_AssociatedFileType_enum_t value)
{
    switch (value) {
    case tflite_AssociatedFileType_UNKNOWN: return "UNKNOWN";
    case tflite_AssociatedFileType_DESCRIPTIONS: return "DESCRIPTIONS";
    case tflite_AssociatedFileType_TENSOR_AXIS_LABELS: return "TENSOR_AXIS_LABELS";
    case tflite_AssociatedFileType_TENSOR_VALUE_LABELS: return "TENSOR_VALUE_LABELS";
    case tflite_AssociatedFileType_TENSOR_AXIS_SCORE_CALIBRATION: return "TENSOR_AXIS_SCORE_CALIBRATION";
    case tflite_AssociatedFileType_VOCABULARY: return "VOCABULARY";
    case tflite_AssociatedFileType_SCANN_INDEX_FILE: return "SCANN_INDEX_FILE";
    default: return "";
    }
}

static inline int tflite_AssociatedFileType_is_known_value(tflite_AssociatedFileType_enum_t value)
{
    switch (value) {
    case tflite_AssociatedFileType_UNKNOWN: return 1;
    case tflite_AssociatedFileType_DESCRIPTIONS: return 1;
    case tflite_AssociatedFileType_TENSOR_AXIS_LABELS: return 1;
    case tflite_AssociatedFileType_TENSOR_VALUE_LABELS: return 1;
    case tflite_AssociatedFileType_TENSOR_AXIS_SCORE_CALIBRATION: return 1;
    case tflite_AssociatedFileType_VOCABULARY: return 1;
    case tflite_AssociatedFileType_SCANN_INDEX_FILE: return 1;
    default: return 0;
    }
}

typedef int8_t tflite_ColorSpaceType_enum_t;
__flatbuffers_define_integer_type(tflite_ColorSpaceType, tflite_ColorSpaceType_enum_t, 8)
#define tflite_ColorSpaceType_UNKNOWN ((tflite_ColorSpaceType_enum_t)INT8_C(0))
#define tflite_ColorSpaceType_RGB ((tflite_ColorSpaceType_enum_t)INT8_C(1))
#define tflite_ColorSpaceType_GRAYSCALE ((tflite_ColorSpaceType_enum_t)INT8_C(2))

static inline const char *tflite_ColorSpaceType_name(tflite_ColorSpaceType_enum_t value)
{
    switch (value) {
    case tflite_ColorSpaceType_UNKNOWN: return "UNKNOWN";
    case tflite_ColorSpaceType_RGB: return "RGB";
    case tflite_ColorSpaceType_GRAYSCALE: return "GRAYSCALE";
    default: return "";
    }
}

static inline int tflite_ColorSpaceType_is_known_value(tflite_ColorSpaceType_enum_t value)
{
    switch (value) {
    case tflite_ColorSpaceType_UNKNOWN: return 1;
    case tflite_ColorSpaceType_RGB: return 1;
    case tflite_ColorSpaceType_GRAYSCALE: return 1;
    default: return 0;
    }
}

typedef int8_t tflite_BoundingBoxType_enum_t;
__flatbuffers_define_integer_type(tflite_BoundingBoxType, tflite_BoundingBoxType_enum_t, 8)
#define tflite_BoundingBoxType_UNKNOWN ((tflite_BoundingBoxType_enum_t)INT8_C(0))
#define tflite_BoundingBoxType_BOUNDARIES ((tflite_BoundingBoxType_enum_t)INT8_C(1))
#define tflite_BoundingBoxType_UPPER_LEFT ((tflite_BoundingBoxType_enum_t)INT8_C(2))
#define tflite_BoundingBoxType_CENTER ((tflite_BoundingBoxType_enum_t)INT8_C(3))

static inline const char *tflite_BoundingBoxType_name(tflite_BoundingBoxType_enum_t value)
{
    switch (value) {
    case tflite_BoundingBoxType_UNKNOWN: return "UNKNOWN";
    case tflite_BoundingBoxType_BOUNDARIES: return "BOUNDARIES";
    case tflite_BoundingBoxType_UPPER_LEFT: return "UPPER_LEFT";
    case tflite_BoundingBoxType_CENTER: return "CENTER";
    default: return "";
    }
}

static inline int tflite_BoundingBoxType_is_known_value(tflite_BoundingBoxType_enum_t value)
{
    switch (value) {
    case tflite_BoundingBoxType_UNKNOWN: return 1;
    case tflite_BoundingBoxType_BOUNDARIES: return 1;
    case tflite_BoundingBoxType_UPPER_LEFT: return 1;
    case tflite_BoundingBoxType_CENTER: return 1;
    default: return 0;
    }
}

typedef int8_t tflite_CoordinateType_enum_t;
__flatbuffers_define_integer_type(tflite_CoordinateType, tflite_CoordinateType_enum_t, 8)
#define tflite_CoordinateType_RATIO ((tflite_CoordinateType_enum_t)INT8_C(0))
#define tflite_CoordinateType_PIXEL ((tflite_CoordinateType_enum_t)INT8_C(1))

static inline const char *tflite_CoordinateType_name(tflite_CoordinateType_enum_t value)
{
    switch (value) {
    case tflite_CoordinateType_RATIO: return "RATIO";
    case tflite_CoordinateType_PIXEL: return "PIXEL";
    default: return "";
    }
}

static inline int tflite_CoordinateType_is_known_value(tflite_CoordinateType_enum_t value)
{
    switch (value) {
    case tflite_CoordinateType_RATIO: return 1;
    case tflite_CoordinateType_PIXEL: return 1;
    default: return 0;
    }
}

typedef int8_t tflite_ScoreTransformationType_enum_t;
__flatbuffers_define_integer_type(tflite_ScoreTransformationType, tflite_ScoreTransformationType_enum_t, 8)
#define tflite_ScoreTransformationType_IDENTITY ((tflite_ScoreTransformationType_enum_t)INT8_C(0))
#define tflite_ScoreTransformationType_LOG ((tflite_ScoreTransformationType_enum_t)INT8_C(1))
#define tflite_ScoreTransformationType_INVERSE_LOGISTIC ((tflite_ScoreTransformationType_enum_t)INT8_C(2))

static inline const char *tflite_ScoreTransformationType_name(tflite_ScoreTransformationType_enum_t value)
{
    switch (value) {
    case tflite_ScoreTransformationType_IDENTITY: return "IDENTITY";
    case tflite_ScoreTransformationType_LOG: return "LOG";
    case tflite_ScoreTransformationType_INVERSE_LOGISTIC: return "INVERSE_LOGISTIC";
    default: return "";
    }
}

static inline int tflite_ScoreTransformationType_is_known_value(tflite_ScoreTransformationType_enum_t value)
{
    switch (value) {
    case tflite_ScoreTransformationType_IDENTITY: return 1;
    case tflite_ScoreTransformationType_LOG: return 1;
    case tflite_ScoreTransformationType_INVERSE_LOGISTIC: return 1;
    default: return 0;
    }
}



struct tflite_AssociatedFile_table { uint8_t unused__; };

static inline size_t tflite_AssociatedFile_vec_len(tflite_AssociatedFile_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_AssociatedFile_table_t tflite_AssociatedFile_vec_at(tflite_AssociatedFile_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_AssociatedFile_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_AssociatedFile)

__flatbuffers_define_string_field(0, tflite_AssociatedFile, name, 0)
__flatbuffers_define_string_field(1, tflite_AssociatedFile, description, 0)
__flatbuffers_define_scalar_field(2, tflite_AssociatedFile, type, tflite_AssociatedFileType, tflite_AssociatedFileType_enum_t, INT8_C(0))
__flatbuffers_define_string_field(3, tflite_AssociatedFile, locale, 0)
__flatbuffers_define_string_field(4, tflite_AssociatedFile, version, 0)

struct tflite_FeatureProperties_table { uint8_t unused__; };

static inline size_t tflite_FeatureProperties_vec_len(tflite_FeatureProperties_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_FeatureProperties_table_t tflite_FeatureProperties_vec_at(tflite_FeatureProperties_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_FeatureProperties_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_FeatureProperties)


struct tflite_ImageSize_table { uint8_t unused__; };

static inline size_t tflite_ImageSize_vec_len(tflite_ImageSize_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_ImageSize_table_t tflite_ImageSize_vec_at(tflite_ImageSize_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_ImageSize_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_ImageSize)

__flatbuffers_define_scalar_field(0, tflite_ImageSize, width, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, tflite_ImageSize, height, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct tflite_ImageProperties_table { uint8_t unused__; };

static inline size_t tflite_ImageProperties_vec_len(tflite_ImageProperties_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_ImageProperties_table_t tflite_ImageProperties_vec_at(tflite_ImageProperties_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_ImageProperties_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_ImageProperties)

__flatbuffers_define_scalar_field(0, tflite_ImageProperties, color_space, tflite_ColorSpaceType, tflite_ColorSpaceType_enum_t, INT8_C(0))
__flatbuffers_define_table_field(1, tflite_ImageProperties, default_size, tflite_ImageSize_table_t, 0)

struct tflite_AudioProperties_table { uint8_t unused__; };

static inline size_t tflite_AudioProperties_vec_len(tflite_AudioProperties_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_AudioProperties_table_t tflite_AudioProperties_vec_at(tflite_AudioProperties_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_AudioProperties_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_AudioProperties)

__flatbuffers_define_scalar_field(0, tflite_AudioProperties, sample_rate, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, tflite_AudioProperties, channels, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct tflite_BoundingBoxProperties_table { uint8_t unused__; };

static inline size_t tflite_BoundingBoxProperties_vec_len(tflite_BoundingBoxProperties_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_BoundingBoxProperties_table_t tflite_BoundingBoxProperties_vec_at(tflite_BoundingBoxProperties_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_BoundingBoxProperties_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_BoundingBoxProperties)

__flatbuffers_define_vector_field(0, tflite_BoundingBoxProperties, index, flatbuffers_uint32_vec_t, 0)
__flatbuffers_define_scalar_field(1, tflite_BoundingBoxProperties, type, tflite_BoundingBoxType, tflite_BoundingBoxType_enum_t, INT8_C(0))
__flatbuffers_define_scalar_field(2, tflite_BoundingBoxProperties, coordinate_type, tflite_CoordinateType, tflite_CoordinateType_enum_t, INT8_C(0))
typedef uint8_t tflite_ContentProperties_union_type_t;
__flatbuffers_define_integer_type(tflite_ContentProperties, tflite_ContentProperties_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, tflite_ContentProperties)
#define tflite_ContentProperties_NONE ((tflite_ContentProperties_union_type_t)UINT8_C(0))
#define tflite_ContentProperties_FeatureProperties ((tflite_ContentProperties_union_type_t)UINT8_C(1))
#define tflite_ContentProperties_ImageProperties ((tflite_ContentProperties_union_type_t)UINT8_C(2))
#define tflite_ContentProperties_BoundingBoxProperties ((tflite_ContentProperties_union_type_t)UINT8_C(3))
#define tflite_ContentProperties_AudioProperties ((tflite_ContentProperties_union_type_t)UINT8_C(4))

static inline const char *tflite_ContentProperties_type_name(tflite_ContentProperties_union_type_t type)
{
    switch (type) {
    case tflite_ContentProperties_NONE: return "NONE";
    case tflite_ContentProperties_FeatureProperties: return "FeatureProperties";
    case tflite_ContentProperties_ImageProperties: return "ImageProperties";
    case tflite_ContentProperties_BoundingBoxProperties: return "BoundingBoxProperties";
    case tflite_ContentProperties_AudioProperties: return "AudioProperties";
    default: return "";
    }
}

static inline int tflite_ContentProperties_is_known_type(tflite_ContentProperties_union_type_t type)
{
    switch (type) {
    case tflite_ContentProperties_NONE: return 1;
    case tflite_ContentProperties_FeatureProperties: return 1;
    case tflite_ContentProperties_ImageProperties: return 1;
    case tflite_ContentProperties_BoundingBoxProperties: return 1;
    case tflite_ContentProperties_AudioProperties: return 1;
    default: return 0;
    }
}


struct tflite_ValueRange_table { uint8_t unused__; };

static inline size_t tflite_ValueRange_vec_len(tflite_ValueRange_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_ValueRange_table_t tflite_ValueRange_vec_at(tflite_ValueRange_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_ValueRange_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_ValueRange)

__flatbuffers_define_scalar_field(0, tflite_ValueRange, min, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(1, tflite_ValueRange, max, flatbuffers_int32, int32_t, INT32_C(0))

struct tflite_Content_table { uint8_t unused__; };

static inline size_t tflite_Content_vec_len(tflite_Content_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_Content_table_t tflite_Content_vec_at(tflite_Content_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_Content_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_Content)

__flatbuffers_define_union_field(flatbuffers_, 1, tflite_Content, content_properties, tflite_ContentProperties, 0)
__flatbuffers_define_table_field(2, tflite_Content, range, tflite_ValueRange_table_t, 0)

struct tflite_NormalizationOptions_table { uint8_t unused__; };

static inline size_t tflite_NormalizationOptions_vec_len(tflite_NormalizationOptions_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_NormalizationOptions_table_t tflite_NormalizationOptions_vec_at(tflite_NormalizationOptions_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_NormalizationOptions_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_NormalizationOptions)

__flatbuffers_define_vector_field(0, tflite_NormalizationOptions, mean, flatbuffers_float_vec_t, 0)
__flatbuffers_define_vector_field(1, tflite_NormalizationOptions, std, flatbuffers_float_vec_t, 0)

struct tflite_ScoreCalibrationOptions_table { uint8_t unused__; };

static inline size_t tflite_ScoreCalibrationOptions_vec_len(tflite_ScoreCalibrationOptions_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_ScoreCalibrationOptions_table_t tflite_ScoreCalibrationOptions_vec_at(tflite_ScoreCalibrationOptions_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_ScoreCalibrationOptions_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_ScoreCalibrationOptions)

__flatbuffers_define_scalar_field(0, tflite_ScoreCalibrationOptions, score_transformation, tflite_ScoreTransformationType, tflite_ScoreTransformationType_enum_t, INT8_C(0))
__flatbuffers_define_scalar_field(1, tflite_ScoreCalibrationOptions, default_score, flatbuffers_float, float, 0.00000000f)

struct tflite_ScoreThresholdingOptions_table { uint8_t unused__; };

static inline size_t tflite_ScoreThresholdingOptions_vec_len(tflite_ScoreThresholdingOptions_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_ScoreThresholdingOptions_table_t tflite_ScoreThresholdingOptions_vec_at(tflite_ScoreThresholdingOptions_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_ScoreThresholdingOptions_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_ScoreThresholdingOptions)

__flatbuffers_define_scalar_field(0, tflite_ScoreThresholdingOptions, global_score_threshold, flatbuffers_float, float, 0.00000000f)

struct tflite_BertTokenizerOptions_table { uint8_t unused__; };

static inline size_t tflite_BertTokenizerOptions_vec_len(tflite_BertTokenizerOptions_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_BertTokenizerOptions_table_t tflite_BertTokenizerOptions_vec_at(tflite_BertTokenizerOptions_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_BertTokenizerOptions_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_BertTokenizerOptions)

__flatbuffers_define_vector_field(0, tflite_BertTokenizerOptions, vocab_file, tflite_AssociatedFile_vec_t, 0)

struct tflite_SentencePieceTokenizerOptions_table { uint8_t unused__; };

static inline size_t tflite_SentencePieceTokenizerOptions_vec_len(tflite_SentencePieceTokenizerOptions_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_SentencePieceTokenizerOptions_table_t tflite_SentencePieceTokenizerOptions_vec_at(tflite_SentencePieceTokenizerOptions_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_SentencePieceTokenizerOptions_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_SentencePieceTokenizerOptions)

__flatbuffers_define_vector_field(0, tflite_SentencePieceTokenizerOptions, sentencePiece_model, tflite_AssociatedFile_vec_t, 0)
__flatbuffers_define_vector_field(1, tflite_SentencePieceTokenizerOptions, vocab_file, tflite_AssociatedFile_vec_t, 0)

struct tflite_RegexTokenizerOptions_table { uint8_t unused__; };

static inline size_t tflite_RegexTokenizerOptions_vec_len(tflite_RegexTokenizerOptions_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_RegexTokenizerOptions_table_t tflite_RegexTokenizerOptions_vec_at(tflite_RegexTokenizerOptions_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_RegexTokenizerOptions_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_RegexTokenizerOptions)

__flatbuffers_define_string_field(0, tflite_RegexTokenizerOptions, delim_regex_pattern, 0)
__flatbuffers_define_vector_field(1, tflite_RegexTokenizerOptions, vocab_file, tflite_AssociatedFile_vec_t, 0)
typedef uint8_t tflite_ProcessUnitOptions_union_type_t;
__flatbuffers_define_integer_type(tflite_ProcessUnitOptions, tflite_ProcessUnitOptions_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, tflite_ProcessUnitOptions)
#define tflite_ProcessUnitOptions_NONE ((tflite_ProcessUnitOptions_union_type_t)UINT8_C(0))
#define tflite_ProcessUnitOptions_NormalizationOptions ((tflite_ProcessUnitOptions_union_type_t)UINT8_C(1))
#define tflite_ProcessUnitOptions_ScoreCalibrationOptions ((tflite_ProcessUnitOptions_union_type_t)UINT8_C(2))
#define tflite_ProcessUnitOptions_ScoreThresholdingOptions ((tflite_ProcessUnitOptions_union_type_t)UINT8_C(3))
#define tflite_ProcessUnitOptions_BertTokenizerOptions ((tflite_ProcessUnitOptions_union_type_t)UINT8_C(4))
#define tflite_ProcessUnitOptions_SentencePieceTokenizerOptions ((tflite_ProcessUnitOptions_union_type_t)UINT8_C(5))
#define tflite_ProcessUnitOptions_RegexTokenizerOptions ((tflite_ProcessUnitOptions_union_type_t)UINT8_C(6))

static inline const char *tflite_ProcessUnitOptions_type_name(tflite_ProcessUnitOptions_union_type_t type)
{
    switch (type) {
    case tflite_ProcessUnitOptions_NONE: return "NONE";
    case tflite_ProcessUnitOptions_NormalizationOptions: return "NormalizationOptions";
    case tflite_ProcessUnitOptions_ScoreCalibrationOptions: return "ScoreCalibrationOptions";
    case tflite_ProcessUnitOptions_ScoreThresholdingOptions: return "ScoreThresholdingOptions";
    case tflite_ProcessUnitOptions_BertTokenizerOptions: return "BertTokenizerOptions";
    case tflite_ProcessUnitOptions_SentencePieceTokenizerOptions: return "SentencePieceTokenizerOptions";
    case tflite_ProcessUnitOptions_RegexTokenizerOptions: return "RegexTokenizerOptions";
    default: return "";
    }
}

static inline int tflite_ProcessUnitOptions_is_known_type(tflite_ProcessUnitOptions_union_type_t type)
{
    switch (type) {
    case tflite_ProcessUnitOptions_NONE: return 1;
    case tflite_ProcessUnitOptions_NormalizationOptions: return 1;
    case tflite_ProcessUnitOptions_ScoreCalibrationOptions: return 1;
    case tflite_ProcessUnitOptions_ScoreThresholdingOptions: return 1;
    case tflite_ProcessUnitOptions_BertTokenizerOptions: return 1;
    case tflite_ProcessUnitOptions_SentencePieceTokenizerOptions: return 1;
    case tflite_ProcessUnitOptions_RegexTokenizerOptions: return 1;
    default: return 0;
    }
}


struct tflite_ProcessUnit_table { uint8_t unused__; };

static inline size_t tflite_ProcessUnit_vec_len(tflite_ProcessUnit_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_ProcessUnit_table_t tflite_ProcessUnit_vec_at(tflite_ProcessUnit_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_ProcessUnit_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_ProcessUnit)

__flatbuffers_define_union_field(flatbuffers_, 1, tflite_ProcessUnit, options, tflite_ProcessUnitOptions, 0)

struct tflite_Stats_table { uint8_t unused__; };

static inline size_t tflite_Stats_vec_len(tflite_Stats_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_Stats_table_t tflite_Stats_vec_at(tflite_Stats_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_Stats_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_Stats)

__flatbuffers_define_vector_field(0, tflite_Stats, max, flatbuffers_float_vec_t, 0)
__flatbuffers_define_vector_field(1, tflite_Stats, min, flatbuffers_float_vec_t, 0)

struct tflite_TensorGroup_table { uint8_t unused__; };

static inline size_t tflite_TensorGroup_vec_len(tflite_TensorGroup_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_TensorGroup_table_t tflite_TensorGroup_vec_at(tflite_TensorGroup_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_TensorGroup_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_TensorGroup)

__flatbuffers_define_string_field(0, tflite_TensorGroup, name, 0)
__flatbuffers_define_vector_field(1, tflite_TensorGroup, tensor_names, flatbuffers_string_vec_t, 0)

struct tflite_TensorMetadata_table { uint8_t unused__; };

static inline size_t tflite_TensorMetadata_vec_len(tflite_TensorMetadata_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_TensorMetadata_table_t tflite_TensorMetadata_vec_at(tflite_TensorMetadata_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_TensorMetadata_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_TensorMetadata)

__flatbuffers_define_string_field(0, tflite_TensorMetadata, name, 0)
__flatbuffers_define_string_field(1, tflite_TensorMetadata, description, 0)
__flatbuffers_define_vector_field(2, tflite_TensorMetadata, dimension_names, flatbuffers_string_vec_t, 0)
__flatbuffers_define_table_field(3, tflite_TensorMetadata, content, tflite_Content_table_t, 0)
__flatbuffers_define_vector_field(4, tflite_TensorMetadata, process_units, tflite_ProcessUnit_vec_t, 0)
__flatbuffers_define_table_field(5, tflite_TensorMetadata, stats, tflite_Stats_table_t, 0)
__flatbuffers_define_vector_field(6, tflite_TensorMetadata, associated_files, tflite_AssociatedFile_vec_t, 0)

struct tflite_CustomMetadata_table { uint8_t unused__; };

static inline size_t tflite_CustomMetadata_vec_len(tflite_CustomMetadata_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_CustomMetadata_table_t tflite_CustomMetadata_vec_at(tflite_CustomMetadata_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_CustomMetadata_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_CustomMetadata)

__flatbuffers_define_string_field(0, tflite_CustomMetadata, name, 0)

struct tflite_SubGraphMetadata_table { uint8_t unused__; };

static inline size_t tflite_SubGraphMetadata_vec_len(tflite_SubGraphMetadata_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_SubGraphMetadata_table_t tflite_SubGraphMetadata_vec_at(tflite_SubGraphMetadata_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_SubGraphMetadata_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_SubGraphMetadata)

__flatbuffers_define_string_field(0, tflite_SubGraphMetadata, name, 0)
__flatbuffers_define_string_field(1, tflite_SubGraphMetadata, description, 0)
__flatbuffers_define_vector_field(2, tflite_SubGraphMetadata, input_tensor_metadata, tflite_TensorMetadata_vec_t, 0)
__flatbuffers_define_vector_field(3, tflite_SubGraphMetadata, output_tensor_metadata, tflite_TensorMetadata_vec_t, 0)
__flatbuffers_define_vector_field(4, tflite_SubGraphMetadata, associated_files, tflite_AssociatedFile_vec_t, 0)
__flatbuffers_define_vector_field(5, tflite_SubGraphMetadata, input_process_units, tflite_ProcessUnit_vec_t, 0)
__flatbuffers_define_vector_field(6, tflite_SubGraphMetadata, output_process_units, tflite_ProcessUnit_vec_t, 0)
__flatbuffers_define_vector_field(7, tflite_SubGraphMetadata, input_tensor_groups, tflite_TensorGroup_vec_t, 0)
__flatbuffers_define_vector_field(8, tflite_SubGraphMetadata, output_tensor_groups, tflite_TensorGroup_vec_t, 0)
__flatbuffers_define_vector_field(9, tflite_SubGraphMetadata, custom_metadata, tflite_CustomMetadata_vec_t, 0)

struct tflite_ModelMetadata_table { uint8_t unused__; };

static inline size_t tflite_ModelMetadata_vec_len(tflite_ModelMetadata_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tflite_ModelMetadata_table_t tflite_ModelMetadata_vec_at(tflite_ModelMetadata_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tflite_ModelMetadata_table_t, vec, i, 0)
__flatbuffers_table_as_root(tflite_ModelMetadata)

__flatbuffers_define_string_field(0, tflite_ModelMetadata, name, 0)
__flatbuffers_define_string_field(1, tflite_ModelMetadata, description, 0)
__flatbuffers_define_string_field(2, tflite_ModelMetadata, version, 0)
__flatbuffers_define_vector_field(3, tflite_ModelMetadata, subgraph_metadata, tflite_SubGraphMetadata_vec_t, 0)
__flatbuffers_define_string_field(4, tflite_ModelMetadata, author, 0)
__flatbuffers_define_string_field(5, tflite_ModelMetadata, license, 0)
__flatbuffers_define_vector_field(6, tflite_ModelMetadata, associated_files, tflite_AssociatedFile_vec_t, 0)
__flatbuffers_define_string_field(7, tflite_ModelMetadata, min_parser_version, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* TFLITE_READER_H */
